# Generated by Django 2.2.9 on 2020-07-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=2000)),
                ('article_uuid', models.CharField(max_length=20)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
