# Generated by Django 2.2.9 on 2020-07-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0000_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.TextField()),
                ('body', models.TextField()),
                ('headline', models.CharField(max_length=300)),
                ('byline', models.CharField(max_length=300)),
                ('image_url', models.CharField(max_length=500)),
                ('pitch_text', models.CharField(max_length=500)),
                ('publish_at', models.DateTimeField(verbose_name='published date')),
                ('uuid', models.CharField(max_length=200)),
                ('instruments', models.CharField(max_length=500)),
            ],
        ),
    ]
